"""[ADDITION] user_connection_name field added.

Revision ID: 51cc1704658c
Revises: ea4258387ace
Create Date: 2025-03-24 13:06:52.253602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cc1704658c'
down_revision: Union[str, None] = 'ea4258387ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_connection', sa.Column('user_connection_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users_connection', ['user_connection_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_connection', type_='unique')
    op.drop_column('users_connection', 'user_connection_name')
    # ### end Alembic commands ###
