"""[CORRECTION] corrected the relation between User and User connection foreign key

Revision ID: d85c068df8ff
Revises: 51cc1704658c
Create Date: 2025-03-25 08:25:32.685380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85c068df8ff'
down_revision: Union[str, None] = '51cc1704658c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
